"use client"

// Type definitions for courier dashboard
interface User {
  id: string;
  name?: string;
  email?: string;
  role?: string;
  branch?: string; // Optional branch field
}

interface Shipment {
  awb_number: string;
  current_status: string;
  receiver_name: string;
  receiver_phone: string;
  receiver_address: string;
  updated_at?: string;
  created_at?: string;
}

interface ShipmentHistory {
  awb_number: string;
  status: string;
  created_at: string;
  location?: string;
}

import { useState, useEffect, useCallback, useRef } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ScanAlt, Search, ChevronDown, ChevronUp, Close, DeliveryParcel, CheckmarkFilled, PendingFilled, Logout, Chat, Location, Task, Package } from "@carbon/icons-react"
import { supabaseClient } from "@/lib/auth"
import { BulkUpdateModal } from "./bulk-update-modal"
import { ContinuousScanModal } from "./continuous-scan-modal"
import { CourierPickupForm } from "./courier-pickup-form"
import { PushNotification } from "./push-notification"
import { useToast } from "@/hooks/use-toast"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { useExternalLinks } from "@/hooks/use-external-links"
import { isInCapacitor, handleCapacitorLogout } from "@/lib/capacitor-utils"
import { Input } from "@/components/ui/input"

// Component for WhatsApp button
const WhatsAppButton = ({ phoneNumber, recipientName, courierName }: { phoneNumber: string; recipientName: string; courierName: string }) => {
  const { openWhatsApp } = useExternalLinks();
  
  // Don't show if:
  // 1. Phone number is empty, N/A, or Auto Generated
  // 2. Phone number has less than 10 digits after cleaning
  if (!phoneNumber || 
      phoneNumber === "N/A" || 
      phoneNumber.toLowerCase().includes("auto generated") ||
      phoneNumber.toLowerCase().includes("autogenerated")) {
    return null;
  }
  
  const cleanNumber = phoneNumber.replace(/\D/g, "");
  if (cleanNumber.length < 10) {
    return null;
  }
  
  const message = `Halo pak ${recipientName}, saya ${courierName} kurir bce express. Yg akan mengirimkan paket bapak. Apakah alamat sudah sesuai di alamat pak? Atau boleh di kirimkan share lokasi nya?`;
  
  const handleWhatsAppClick = async () => {
    await openWhatsApp(phoneNumber, message);
  };
  
  return (
    <Button
      variant="ghost"
      size="icon"
      className="ml-1 h-7 w-7 text-green-600 hover:text-green-700"
      onClick={handleWhatsAppClick}
      aria-label="WhatsApp"
      title="WhatsApp"
    >
      <Chat className="h-4 w-4" aria-hidden="true" />
      <span className="sr-only">WhatsApp</span>
    </Button>
  );
};

// Component for Maps button
const MapsButton = ({ address }: { address: string }) => {
  const { openMaps } = useExternalLinks();
  
  // Don't show if:
  // 1. Address is empty, N/A, or Auto Generated
  // 2. Address is too short (less than 10 characters to ensure it's properly filled)
  if (!address || 
      address === "N/A" || 
      address.toLowerCase().includes("auto generated") ||
      address.toLowerCase().includes("autogenerated") ||
      address.trim().length < 10) {
    return null;
  }
  
  const handleMapsClick = async () => {
    await openMaps(address);
  };
  
  return (
    <Button
      variant="ghost"
      size="icon"
      className="ml-1 h-7 w-7 text-blue-600 hover:text-blue-700"
      onClick={handleMapsClick}
      aria-label="Maps"
      title="Maps"
    >
      <Location className="h-4 w-4" aria-hidden="true" />
      <span className="sr-only">Maps</span>
    </Button>
  );
};

export function CourierDashboard() {
  const [currentUser, setCurrentUser] = useState<User | null>(null)
  const [completedCount, setCompletedCount] = useState(0)
  const [lastCompletedAwb, setLastCompletedAwb] = useState("")
  const [isBulkModalOpen, setIsBulkModalOpen] = useState(false)
  const [isContinuousScanOpen, setIsContinuousScanOpen] = useState(false)
  const [isDeliveredScanOpen, setIsDeliveredScanOpen] = useState(false)
  const [totalBulkShipments, setTotalBulkShipments] = useState(0)
  const [pendingDeliveries, setPendingDeliveries] = useState(0)
  const [bulkShipmentAwbs, setBulkShipmentAwbs] = useState<Shipment[]>([])
  const [pendingShipments, setPendingShipments] = useState<Shipment[]>([])
  const [showBulkDetails, setShowBulkDetails] = useState(false)
  const [showPendingDetails, setShowPendingDetails] = useState(false)
  const [completedTodayShipments, setCompletedTodayShipments] = useState<ShipmentHistory[]>([])
  const [showCompletedTodayDetails, setShowCompletedTodayDetails] = useState(false)
  const [hasCompletedFirstDelivery, setHasCompletedFirstDelivery] = useState(false)
  const [expandAssignments, setExpandAssignments] = useState(false);
  const [expandPending, setExpandPending] = useState(false);
  const [expandCompleted, setExpandCompleted] = useState(false);
  const [showAllAssignments, setShowAllAssignments] = useState(false);
  const [showAllCompleted, setShowAllCompleted] = useState(false);
  const [isPickupFormOpen, setIsPickupFormOpen] = useState(false);
  const [expandedAwbs, setExpandedAwbs] = useState<Record<string, boolean>>({});
  const assignmentsRef = useRef<HTMLDivElement | null>(null)
  const completedRef = useRef<HTMLDivElement | null>(null)
  const pendingRef = useRef<HTMLDivElement | null>(null)
  const toggleAwbExpand = (awb: string): void => {
    setExpandedAwbs(prev => ({ ...prev, [awb]: !prev[awb] }));
  };

  // Header search state
  const [awbQuery, setAwbQuery] = useState<string>("")
  const [isSearching, setIsSearching] = useState<boolean>(false)
  const [awbSearchResults, setAwbSearchResults] = useState<Shipment[]>([])
  const [showSearchResults, setShowSearchResults] = useState<boolean>(false)

  const [isProfileLoading, setIsProfileLoading] = useState(true)
  const [isShipmentsLoading, setIsShipmentsLoading] = useState(false)
  const refreshTimeout = useRef<NodeJS.Timeout | null>(null)
  const locationUpdateInterval = useRef<NodeJS.Timeout | null>(null)
  const bottomBarRef = useRef<HTMLDivElement | null>(null)
  const [bottomBarHeight, setBottomBarHeight] = useState<number>(0)

  const router = useRouter()
  const { toast } = useToast()

  const loadShipmentData = useCallback(async (user: User) => {
    setIsShipmentsLoading(true)
    try {
      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const todayISOString = today.toISOString()
      const yesterday = new Date(today)
      yesterday.setDate(yesterday.getDate() - 1)
      const yesterdayISOString = yesterday.toISOString()
      
      const courierId = user?.id
      const courierName = user?.name || user?.email?.split("@")[0] || ""

      // Add timeout to all database queries (OPTIMASI: Kurangi timeout untuk device low-end)
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Database timeout')), 8000)  // Kurangi dari 15 detik ke 8 detik
      );

      // Get today's bulk shipments (OPTIMASI: Kurangi limit untuk performa)
      const bulkShipmentsPromise = supabaseClient
        .from("shipments")
        .select("awb_number, current_status, receiver_name, receiver_phone, receiver_address, updated_at")  // Hapus created_at yang tidak perlu
        .eq("courier_id", courierId)
        .gte("created_at", todayISOString)
        .not("current_status", "in", '("delivered", "cancelled")')
        .order("updated_at", { ascending: false })
        .limit(30);  // Naikkan limit dari 15 ke 30 sesuai permintaan user

      // Get pending deliveries (OPTIMASI: Kurangi field yang diambil)
      const pendingPromise = supabaseClient
        .from("shipments")
        .select("awb_number, current_status, receiver_name, receiver_phone, receiver_address, created_at")
        .eq("courier_id", courierId)
        .in("current_status", ["out_for_delivery", "shipped"])
        .lt("created_at", todayISOString)
        .order("created_at", { ascending: false })
        .limit(30);  // Naikkan limit dari 15 ke 30 sesuai permintaan user

      // Get completed today (OPTIMASI: Kurangi field yang diambil)
      // Delivered today for this courier (lightweight: use shipments table)
      const shipmentsDeliveredTodayPromise = supabaseClient
        .from("shipments")
        .select("awb_number, updated_at")
        .eq("courier_id", courierId)
        .eq("current_status", "delivered")
        .gte("updated_at", todayISOString)
        .order("updated_at", { ascending: false });

      // Execute all queries in parallel with timeout
      const [bulkShipmentsResult, pendingResult, completedTodayResult] = await Promise.allSettled([
        Promise.race([bulkShipmentsPromise, timeoutPromise]),
        Promise.race([pendingPromise, timeoutPromise]),
        Promise.race([shipmentsDeliveredTodayPromise, timeoutPromise])
      ]);

      // Handle bulk shipments result
      if (bulkShipmentsResult.status === 'fulfilled') {
        const { data: bulkShipmentsData, error: bulkShipmentsError } = bulkShipmentsResult.value as { data: Shipment[] | null; error: unknown };
        if (bulkShipmentsError) {
          setTotalBulkShipments(0);
          setBulkShipmentAwbs([]);
        } else {
          setTotalBulkShipments(bulkShipmentsData?.length || 0);
          setBulkShipmentAwbs(bulkShipmentsData || []);
        }
      } else {
        setTotalBulkShipments(0);
        setBulkShipmentAwbs([]);
      }

      // Handle pending deliveries result
      if (pendingResult.status === 'fulfilled') {
        const { data: pendingData, error: pendingError } = pendingResult.value as { data: Shipment[] | null; error: unknown };
        if (pendingError) {
          setPendingDeliveries(0);
          setPendingShipments([]);
        } else {
          setPendingDeliveries(pendingData?.length || 0);
          setPendingShipments(pendingData || []);
        }
      } else {
        setPendingDeliveries(0);
        setPendingShipments([]);
      }

      // Handle completed today result (based on shipments table)
      if (completedTodayResult.status === 'fulfilled') {
        const { data: deliveredTodayData, error: deliveredError } = completedTodayResult.value as { data: { awb_number: string; updated_at: string }[] | null; error: unknown };
        if (deliveredError) {
          setCompletedCount(0);
          setCompletedTodayShipments([]);
          setLastCompletedAwb("");
        } else {
          const list = deliveredTodayData || [];
          setCompletedCount(list.length);
          // Map to ShipmentHistory shape for UI
          const mapped: ShipmentHistory[] = list.map((s) => ({
            awb_number: s.awb_number,
            status: "delivered",
            created_at: s.updated_at,
            location: undefined,
          }));
          setCompletedTodayShipments(mapped);
          if (list.length > 0) {
            const latest = [...list].sort((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime())[0];
            setLastCompletedAwb(latest.awb_number);
          } else {
            setLastCompletedAwb("");
          }
        }
      } else {
        setCompletedCount(0);
        setCompletedTodayShipments([]);
        setLastCompletedAwb("");
      }

    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to load shipment data. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsShipmentsLoading(false);
    }
  }, [toast]);

  const debouncedRefresh = useCallback((user: User) => {
    if (refreshTimeout.current) {
      clearTimeout(refreshTimeout.current)
    }
    
    // OPTIMASI: Percepat refresh setelah scan untuk UX yang lebih responsif
    const timeout = setTimeout(() => {
      loadShipmentData(user)
      refreshTimeout.current = null
    }, 800)  // Turunkan dari 2 detik ke 800ms untuk responsifitas lebih baik
    
    refreshTimeout.current = timeout
  }, [loadShipmentData])

  // Function to check if courier has completed any deliveries today
  const checkFirstDeliveryStatus = useCallback(async (user: User) => {
    try {
      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const todayISOString = today.toISOString()
      const courierName = user?.name || user?.email?.split("@")[0] || ""

      const { data: completedToday, error } = await supabaseClient
        .from("shipment_history")
        .select("awb_number")
        .eq("status", "delivered")
        .ilike("notes", `%${courierName}%`)
        .gte("created_at", todayISOString)
        .limit(1)

      if (!error && completedToday && completedToday.length > 0) {
        setHasCompletedFirstDelivery(true)
      } else {
        setHasCompletedFirstDelivery(false)
      }
    } catch (error) {
      setHasCompletedFirstDelivery(false)
    }
  }, [])

  const loadUserProfile = useCallback(async () => {
    setIsProfileLoading(true);
    try {
      const { data: sessionData, error: sessionError } = await supabaseClient.auth.getSession();

      if (sessionError) {
        toast({
          title: "Error Session",
          description: sessionError.message || "Failed to get session. Please log in again.",
          variant: "destructive",
        });
        setIsProfileLoading(false);
        return;
      }
      if (!sessionData?.session?.user?.id) {
        router.push("/courier");
        setIsProfileLoading(false);
        return;
      }

      const userId = sessionData.session.user.id;
      const { data: userData, error: userError } = await supabaseClient
        .from("users")
        .select("*")
        .eq("id", userId)
        .single();

      if (userError) {
        toast({
          title: "Error User Data",
          description: userError.message || "Failed to fetch user data. Check RLS on 'users' table.",
          variant: "destructive",
        });
        setIsProfileLoading(false);
        return;
      }

      setCurrentUser(userData);
      setIsProfileLoading(false);
      
      // Check first delivery status
      await checkFirstDeliveryStatus(userData);
      
      loadShipmentData(userData);

    } catch (err: unknown) {
      setIsProfileLoading(false);
      const errorMessage = err instanceof Error ? err.message : "Failed to load user profile. Please try again.";
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive",
      });
    }
  }, [loadShipmentData, router, toast, checkFirstDeliveryStatus]);

  const runAwbSearch = useCallback(async (query: string, courierId: string) => {
    const q = query.trim()
    if (q.length < 4) {
      setAwbSearchResults([])
      setShowSearchResults(false)
      return
    }
    setIsSearching(true)
    try {
      // Search by AWB number or receiver name for current courier
      const { data, error } = await supabaseClient
        .from("shipments")
        .select("awb_number, current_status, receiver_name, receiver_phone, receiver_address, created_at, updated_at")
        .eq("courier_id", courierId)
        .or(`awb_number.ilike.%${q}%,receiver_name.ilike.%${q}%,receiver_address.ilike.%${q}%`)
        .order("updated_at", { ascending: false })
        .limit(20)

      if (error) {
        setAwbSearchResults([])
        setShowSearchResults(false)
        toast({ title: "Search failed", description: error.message, variant: "destructive" })
        return
      }
      setAwbSearchResults(data || [])
      setShowSearchResults(true)
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unknown error"
      toast({ title: "Search error", description: msg, variant: "destructive" })
    } finally {
      setIsSearching(false)
    }
  }, [toast])

  // Geolocation update logic
  const updateCourierLocation = useCallback(async (userId: string) => {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          const { latitude, longitude } = position.coords;
          try {
            // Attempt to update existing record
            const { data: updatedData, error: updateError } = await supabaseClient
              .from('courier_current_locations')
              .update({
                latitude: latitude,
                longitude: longitude,
                updated_at: new Date().toISOString()
              })
              .eq('courier_id', userId)
              .select()
              .maybeSingle(); // Use maybeSingle to get null if no row found

            if (updateError) {
              // If it's a specific error for "no rows updated" (e.g., PGRST116 for PostgREST), then attempt insert
              // Note: supabase-js may not always expose PGRST116 explicitly, but `!updatedData` check handles no matching row.
              const { error: insertError } = await supabaseClient
                .from('courier_current_locations')
                .insert({
                  courier_id: userId,
                  latitude: latitude,
                  longitude: longitude
                });
              if (insertError) {
                toast({
                  title: "Location Save Failed",
                  description: insertError.message || "Could not save current location. Check RLS for INSERT.",
                  variant: "destructive",
                });
              }
            } else if (updatedData) { // If update was successful and data was returned
            } else { // If update was successful but no data was returned (e.g., no matching row for update)
              const { error: insertError } = await supabaseClient
                .from('courier_current_locations')
                .insert({
                  courier_id: userId,
                  latitude: latitude,
                  longitude: longitude
                });
              if (insertError) {
                toast({
                  title: "Location Save Failed",
                  description: insertError.message || "Could not save current location. Check RLS for INSERT.",
                  variant: "destructive",
                });
              }
            }

          } catch (dbError: unknown) {
            const errorMessage = dbError instanceof Error ? dbError.message : "An unexpected database error occurred for location.";
            toast({
              title: "Location DB Error",
              description: errorMessage,
              variant: "destructive",
            });
          }
        },
        (error) => {
          if (error.code === error.PERMISSION_DENIED) {
            toast({
              title: "Geolocation Denied",
              description: "Please allow location access to enable live tracking.",
              variant: "default",
            });
          } else {
            toast({
              title: "Geolocation Error",
              description: error.message || "Could not get current location.",
              variant: "destructive",
            });
          }
        },
        {
          enableHighAccuracy: true,
          timeout: 10000, // 10 seconds
          maximumAge: 0 // No cache
        }
      );
    } else {
      toast({
        title: "Geolocation Not Supported",
        description: "Your browser does not support Geolocation.",
        variant: "destructive",
      });
    }
  }, [toast]);

  useEffect(() => {
    loadUserProfile();

    // Cleanup function
    return () => {
      if (refreshTimeout.current) {
        clearTimeout(refreshTimeout.current);
      }
      if (locationUpdateInterval.current) {
        clearInterval(locationUpdateInterval.current);
        locationUpdateInterval.current = null;
      }
    };
  }, [loadUserProfile]);

  // Measure bottom bar height to avoid content being covered on small devices
  useEffect(() => {
    const measure = () => {
      const h = bottomBarRef.current?.offsetHeight ?? 0
      setBottomBarHeight(h)
    }
    measure()
    window.addEventListener("resize", measure)
    return () => window.removeEventListener("resize", measure)
  }, [])

  // Separate useEffect for location tracking that depends on hasCompletedFirstDelivery
  useEffect(() => {
    const setupLocationUpdates = async () => {
      if (!hasCompletedFirstDelivery) {
        // Clear any existing interval if tracking should be disabled
        if (locationUpdateInterval.current) {
          clearInterval(locationUpdateInterval.current);
          locationUpdateInterval.current = null;
        }
        return;
      }

      const { data: sessionData } = await supabaseClient.auth.getSession();
      if (!sessionData?.session?.user?.id) return;

      const userId = sessionData.session.user.id;

      // Initial location update
      updateCourierLocation(userId);

      // Set up interval for periodic updates (OPTIMASI: Lebih jarang untuk low-end devices)
      if (!locationUpdateInterval.current) {
        locationUpdateInterval.current = setInterval(() => {
          updateCourierLocation(userId);
        }, 60000);  // Ubah dari 30 detik ke 60 detik untuk menghemat battery dan performa
      }
    };

    setupLocationUpdates();

    // Cleanup interval on dependency change
    return () => {
      if (locationUpdateInterval.current) {
        clearInterval(locationUpdateInterval.current);
        locationUpdateInterval.current = null;
      }
    };
  }, [hasCompletedFirstDelivery, updateCourierLocation]);

  // Cari manual: Hanya mulai saat user menekan Enter (tidak auto-search saat mengetik)

  const handleLogout = async () => {
    // Check if running in Capacitor iframe context
    if (isInCapacitor()) {
      console.warn('CourierDashboard: Using Capacitor logout flow');
      
      await handleCapacitorLogout(async () => {
        await supabaseClient.auth.signOut()
        // Clear saved credentials
        localStorage.removeItem("courierCredentials")
        // Set flag to prevent auto-redirect
        sessionStorage.setItem("courierJustLoggedOut", "true")
      });
      
      // Don't use router.push in Capacitor context
      // Parent container will handle navigation
      return;
    }

    // Normal web browser logout flow
    console.warn('CourierDashboard: Using web browser logout flow');
    
    try {
      // Set flag first before signOut
      sessionStorage.setItem("courierJustLoggedOut", "true")
      await supabaseClient.auth.signOut()
      // Clear saved credentials
      localStorage.removeItem("courierCredentials")
      // Force page reload to clear any cached state
      window.location.href = "/courier"
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to logout. Please try again.",
        variant: "destructive",
      });
    }
  }

  const refreshData = () => {
    if (currentUser) {
      debouncedRefresh(currentUser)
    }
  }

  const handleBulkUpdateSuccess = (count: number) => {
    if (currentUser) {
      debouncedRefresh(currentUser)
    }
  }

  const handlePickupSuccess = () => {
    if (currentUser) {
      // Refresh data after successful pickup
      loadShipmentData(currentUser)
    }
  }

  const handleContinuousScanSuccess = () => {
    if (currentUser) {
      // Immediate refresh untuk scan success agar lebih responsif
      loadShipmentData(currentUser)
    }
  }

  const renderShipmentCard = (shipment: Shipment, type: "bulk" | "pending") => {
    const courierName = currentUser?.name || currentUser?.email?.split("@")[0] || ""
    const isExpanded = !!expandedAwbs[shipment.awb_number];
    
    return (
      <div key={shipment.awb_number} className="border border-white/60 rounded-lg p-2 mb-2 bg-white/70 backdrop-blur-md dark:bg-slate-700/70 dark:border-slate-600">
        <div className="flex justify-between items-start mb-1">
          <div>
            <p className="font-semibold text-sm">{shipment.awb_number}</p>
            <p className="text-xs text-slate-800 dark:text-slate-200 truncate">{shipment.receiver_name}</p>
          </div>
          <Badge variant={shipment.current_status === "out_for_delivery" ? "default" : "secondary"} className="text-xs">
            {shipment.current_status === "out_for_delivery" ? "OFD" : shipment.current_status}
          </Badge>
        </div>
        <p
          role="button"
          tabIndex={0}
          aria-expanded={isExpanded}
          onClick={() => toggleAwbExpand(shipment.awb_number)}
          onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleAwbExpand(shipment.awb_number); } }}
          className={`text-xs text-slate-700 dark:text-slate-300 mb-1 ${isExpanded ? 'whitespace-normal break-words' : 'truncate cursor-pointer hover:underline'}`}
        >
          {shipment.receiver_address}
        </p>
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <WhatsAppButton 
              phoneNumber={shipment.receiver_phone} 
              recipientName={shipment.receiver_name}
              courierName={courierName}
            />
            <MapsButton address={shipment.receiver_address} />
          </div>
          {/* OPTIMASI: Tampilkan tanggal lebih sederhana */}
          <p className="text-xs text-slate-600 dark:text-slate-400">
            {type === "bulk" ? 
              (shipment.updated_at ? new Date(shipment.updated_at).toLocaleDateString('id-ID') : "") :
              (shipment.created_at ? new Date(shipment.created_at).toLocaleDateString('id-ID') : "")
            }
          </p>
        </div>
      </div>
    )
  }

  const renderCompletedCard = (shipment: ShipmentHistory) => {
    return (
      <div key={shipment.awb_number} className="border rounded-lg p-2 mb-2 bg-green-50">
        <div className="flex justify-between items-start mb-1">
          <div>
            <p className="font-semibold text-sm">{shipment.awb_number}</p>
            <p className="text-xs text-green-600">{shipment.status}</p>
          </div>
          <Badge variant="outline" className="bg-green-100 text-green-800 text-xs">
            ✓
          </Badge>
        </div>
        {/* OPTIMASI: Tampilkan lokasi singkat */}
        {shipment.location && (
          <p className="text-xs text-gray-500 mb-1 truncate">{shipment.location}</p>
        )}
        {/* OPTIMASI: Format tanggal sederhana */}
        <p className="text-xs text-gray-400">
          {new Date(shipment.created_at).toLocaleDateString('id-ID')}
        </p>
      </div>
    )
  }

  if (isProfileLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin h-8 w-8 text-gray-600 flex items-center justify-center" aria-label="Loading">
          <PendingFilled className="h-6 w-6" />
        </div>
      </div>
    )
  }

  if (!currentUser) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p>Please log in to access the courier dashboard.</p>
      </div>
    )
  }

  const displayName = currentUser?.name || currentUser?.email?.split("@")[0] || ""
  const emailDisplay = currentUser?.email || ""
  // Logo URL 
  const logoUrl = "/images/bce-logo.png";

  // Sort assignments by created_at ASC (oldest first)
  const sortedAssignments = [...bulkShipmentAwbs].sort((a, b) => {
    const aDate = a.created_at ? new Date(a.created_at).getTime() : 0;
    const bDate = b.created_at ? new Date(b.created_at).getTime() : 0;
    return aDate - bDate;
  });

  return (
    <div
      className="relative min-h-screen bg-[#0E325E] dark:bg-slate-900 pb-24 md:pb-2 overflow-x-hidden"
      style={{ paddingBottom: `calc(${bottomBarHeight}px + env(safe-area-inset-bottom))` }}
    >
      {/* Push Notification Component */}
      <PushNotification userId={currentUser.id} />
      {/* Header with AWB search and scan icon */}
  <header className="px-4 py-3 bg-gradient-to-tr from-[#1C7FA6] via-[#1969A9] to-[#0D47A1] text-white rounded-b-2xl shadow-sm border-b border-white/10 sticky top-0 z-10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <img src={logoUrl} alt="BCE Logo" width={32} height={32} className="rounded brightness-0 invert" />
            <div className="flex flex-col leading-tight">
              <span className="text-[11px] text-white/80">Hi,</span>
              <span className="text-sm font-semibold text-white truncate max-w-[140px]">{displayName}</span>
            </div>
          </div>
          <div className="flex-1 text-center">
            {lastCompletedAwb && (
              <div className="text-xs text-white/80 mt-1">
                Last AWB: <span className="font-mono">{lastCompletedAwb}</span>
              </div>
            )}
          </div>
          <Button
            variant="ghost"
            onClick={handleLogout}
            className="h-8 px-2 text-xs font-bold text-white"
            aria-label="Logout"
            title="Logout"
          >
            <Logout className="h-5 w-5" aria-hidden="true" />
          </Button>
        </div>
        {/* Search row */}
        <div className="mt-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" aria-hidden="true" />
            <Input
              value={awbQuery}
              onChange={(e) => setAwbQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && currentUser) {
                  const q = awbQuery.trim()
                  if (q.length >= 4) {
                    runAwbSearch(q, currentUser.id)
                  }
                }
                if (e.key === 'Escape') {
                  setAwbQuery("")
                  setAwbSearchResults([])
                  setShowSearchResults(false)
                }
              }}
              placeholder="Cari AWB / nama penerima"
              className="pl-12 pr-10 h-10 py-2 text-[13px] leading-5 bg-white text-slate-800 border-slate-200 placeholder:text-slate-500 placeholder:text-[13px]"
              inputMode="search"
              enterKeyHint="search"
            />
            <button
              type="button"
              aria-label="Scan Resi (Delivered)"
              title="Scan Resi (Delivered)"
              onClick={() => setIsDeliveredScanOpen(true)}
              className="absolute right-0.5 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center rounded-md text-gray-600 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <ScanAlt size={16} aria-hidden="true" className="pointer-events-none" />
              <span className="sr-only">Scan</span>
            </button>
          </div>
        </div>
      </header>

  

  {/* Search results */}
      {showSearchResults && (
        <div className="px-3 pt-3">
          <Card className="border border-white/60 bg-white/70 backdrop-blur-md dark:bg-slate-800/70 dark:border-slate-600">
            <CardContent className="pt-4">
              <div className="flex items-center justify-between mb-2">
                <div className="text-sm font-semibold text-slate-800 dark:text-slate-200">Hasil Pencarian ({awbSearchResults.length})</div>
                <Button variant="ghost" size="sm" onClick={() => { setShowSearchResults(false); setAwbQuery(""); }} className="h-7 px-2 text-xs">Tutup</Button>
              </div>
              {isSearching ? (
                <div className="flex flex-col gap-2">
                  {[0,1].map((i) => (
                    <div key={`search-skel-${i}`} className="flex items-center justify-between bg-white/70 rounded-lg border border-white/60 px-3 py-2">
                      <div className="min-w-0 flex-1">
                        <Skeleton className="h-4 w-40 mb-1" />
                        <Skeleton className="h-3 w-28 mb-1" />
                        <Skeleton className="h-3 w-56" />
                      </div>
                      <Skeleton className="h-8 w-16 ml-2 rounded" />
                    </div>
                  ))}
                </div>
              ) : awbSearchResults.length === 0 ? (
                <div className="text-sm text-gray-400">Tidak ada hasil.</div>
              ) : (
                <div className="flex flex-col gap-2">
                  {awbSearchResults.map((s) => (
                    <div key={s.awb_number} className="flex items-center justify-between bg-white/70 rounded-lg border border-white/60 px-3 py-2 dark:bg-slate-700/70 dark:border-slate-600">
                      <div className="min-w-0">
                        <div className="font-mono font-bold text-blue-700 dark:text-blue-300 text-sm">{s.awb_number}</div>
                        <div className="text-xs text-slate-800 dark:text-slate-200 truncate">{s.receiver_name}</div>
                        <div className={`text-[11px] ${s.current_status === 'delivered' ? 'text-green-700 dark:text-green-400' : s.current_status === 'out_for_delivery' ? 'text-yellow-700 dark:text-yellow-400' : 'text-slate-600 dark:text-slate-400'}`}>{s.current_status}</div>
                        <div
                          role="button"
                          tabIndex={0}
                          aria-expanded={!!expandedAwbs[s.awb_number]}
                          onClick={() => toggleAwbExpand(s.awb_number)}
                          onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleAwbExpand(s.awb_number); } }}
                          className={`text-[11px] text-slate-700 dark:text-slate-300 ${expandedAwbs[s.awb_number] ? 'whitespace-normal break-words' : 'truncate cursor-pointer hover:underline'}`}
                        >
                          {s.receiver_address}
                        </div>
                      </div>
                      <Button
                        size="sm"
                        className="bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md ml-2 h-8 px-3 text-xs"
                        onClick={() => router.push(`/courier/update?awb=${s.awb_number}`)}
                      >
                        Update
                      </Button>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* Quick Stats as Accordions */}
  <div className="flex flex-col gap-3 px-3 py-3">
  {/* Assignments Card */}
  <div ref={assignmentsRef} style={{scrollMarginBottom: bottomBarHeight + 24}} className="bg-white/70 backdrop-blur-md rounded-xl shadow-sm border border-white/60 px-4 py-3 dark:bg-slate-800/70 dark:border-slate-600">
    <button className="flex items-center w-full justify-between z-10 relative" onClick={() => setExpandAssignments(v => { const n=!v; if(!v && assignmentsRef.current){ assignmentsRef.current.scrollIntoView({behavior:'smooth', block:'nearest'});} return n; })}>
            <div className="flex items-center gap-3 flex-1 min-w-0">
              <div className="h-6 w-6 text-indigo-600 dark:text-indigo-400 flex items-center justify-center flex-shrink-0" aria-label="Assignments">
                <DeliveryParcel className="h-5 w-5" aria-hidden="true" />
              </div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-200">Assignments</div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <div className="text-2xl font-bold text-gray-900 dark:text-white tabular-nums min-w-[40px] text-right">{totalBulkShipments}</div>
              {expandAssignments ? <ChevronUp className="h-6 w-6 text-gray-400 dark:text-gray-300" /> : <ChevronDown className="h-6 w-6 text-gray-400 dark:text-gray-300" />}
            </div>
          </button>
          {expandAssignments && (
            <div className="mt-3 flex flex-col gap-2 z-10 relative">
              {isShipmentsLoading ? (
                <div className="flex flex-col gap-2">
                  {[0,1,2].map((i) => (
                    <div key={`assign-skel-${i}`} className="flex items-center justify-between bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-100 dark:border-slate-700 px-3 py-2">
                      <div className="flex-1 min-w-0">
                        <Skeleton className="h-4 w-40 mb-1" />
                        <Skeleton className="h-3 w-28 mb-1" />
                        <Skeleton className="h-3 w-56" />
                      </div>
                      <Skeleton className="h-8 w-16 ml-2 rounded" />
                    </div>
                  ))}
                </div>
              ) : sortedAssignments.length === 0 ? (
                <div className="text-slate-600 dark:text-slate-400 text-sm">No assignments for today.</div>
              ) : (
                <>
                  {sortedAssignments.slice(0, showAllAssignments ? sortedAssignments.length : 5).map((shipment) => (
                    <div key={shipment.awb_number} style={{scrollMarginBottom: bottomBarHeight + 24}} className="flex items-center justify-between bg-white/70 rounded-lg border border-white/60 px-3 py-2 dark:bg-slate-700/70 dark:border-slate-600">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <div className="font-mono font-bold text-blue-700 dark:text-blue-300 text-sm">{shipment.awb_number}</div>
                          {shipment.current_status && (
                            <Badge variant="outline" className="text-[10px] px-2 py-0.5 capitalize">
                              {shipment.current_status.replaceAll('_',' ')}
                            </Badge>
                          )}
                        </div>
                        <div className="text-xs text-slate-800 dark:text-slate-200 truncate">{shipment.receiver_name}</div>
                        <div
                          role="button"
                          tabIndex={0}
                          aria-expanded={!!expandedAwbs[shipment.awb_number]}
                          onClick={() => toggleAwbExpand(shipment.awb_number)}
                          onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleAwbExpand(shipment.awb_number); } }}
                          className={`text-xs text-slate-700 dark:text-slate-300 ${expandedAwbs[shipment.awb_number] ? 'whitespace-normal break-words' : 'truncate cursor-pointer hover:underline'}`}
                        >
                          {shipment.receiver_address}
                        </div>
                        <div className="flex gap-1 mt-1">
                          <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                          <MapsButton address={shipment.receiver_address} />
                        </div>
                      </div>
                      <Button
                        size="sm"
                        className="bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md ml-2 h-8 px-3 text-xs"
                        onClick={() => router.push(`/courier/update?awb=${shipment.awb_number}`)}
                      >
                        Update
                      </Button>
                    </div>
                  ))}
                  {sortedAssignments.length > 5 && (
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => setShowAllAssignments(!showAllAssignments)}
                      className="mt-2 text-xs"
                    >
                      {showAllAssignments ? `Show Less` : `Show ${sortedAssignments.length - 5} More`}
                    </Button>
                  )}
                </>
              )}
            </div>
          )}
        </div>
  {/* Completed Card */}
  <div ref={completedRef} style={{scrollMarginBottom: bottomBarHeight + 24}} className="bg-white/70 backdrop-blur-md rounded-xl shadow-sm border border-white/60 px-4 py-3 dark:bg-slate-800/70 dark:border-slate-600">
    <button className="flex items-center w-full justify-between z-10 relative" onClick={() => setExpandCompleted(v => { const n=!v; if(!v && completedRef.current){ completedRef.current.scrollIntoView({behavior:'smooth', block:'nearest'});} return n; })}>
            <div className="flex items-center gap-3 flex-1 min-w-0">
              <div className="h-6 w-6 text-green-600 dark:text-green-400 flex items-center justify-center flex-shrink-0" aria-label="Completed">
                <CheckmarkFilled className="h-5 w-5" aria-hidden="true" />
              </div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-200">Completed</div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <div className="text-2xl font-bold text-gray-900 dark:text-white tabular-nums min-w-[40px] text-right">{completedCount}</div>
              {expandCompleted ? <ChevronUp className="h-6 w-6 text-gray-400 dark:text-gray-300" /> : <ChevronDown className="h-6 w-6 text-gray-400 dark:text-gray-300" />}
            </div>
          </button>
          {expandCompleted && (
            <div className="mt-3 flex flex-col gap-2 z-10 relative">
              {isShipmentsLoading ? (
                <div className="flex flex-col gap-2">
                  {[0,1].map((i) => (
                    <div key={`completed-skel-${i}`} className="flex items-center justify-between bg-white/70 dark:bg-green-900/40 rounded-lg border border-white/60 dark:border-green-700 px-3 py-2">
                      <div className="flex-1 min-w-0">
                        <Skeleton className="h-4 w-40 mb-1" />
                        <Skeleton className="h-3 w-24 mb-1" />
                        <Skeleton className="h-3 w-36" />
                      </div>
                      <div className="ml-2">
                        <Skeleton className="h-8 w-8 rounded-full" />
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <>
                  {completedTodayShipments.slice(0, 5).map((shipment) => (
                    <div key={shipment.awb_number} style={{scrollMarginBottom: bottomBarHeight + 24}} className="flex items-center justify-between bg-white/70 rounded-lg border border-white/60 px-3 py-2 dark:bg-slate-700/70 dark:border-slate-600">
                      <div className="flex-1 min-w-0">
                        <div className="font-mono font-bold text-green-700 dark:text-green-300 text-sm">{shipment.awb_number}</div>
                        <div className="text-xs text-green-700 dark:text-green-400">{shipment.status}</div>
                        {shipment.location && (
                          <div className="text-xs text-slate-700 dark:text-slate-300 truncate mt-1">{shipment.location}</div>
                        )}
                        <div className="text-xs text-slate-600 dark:text-slate-400 mt-1">
                          {new Date(shipment.created_at).toLocaleString('id-ID', { 
                            day: '2-digit', 
                            month: '2-digit', 
                            hour: '2-digit', 
                            minute: '2-digit' 
                          })}
                        </div>
                      </div>
                      <div className="bg-green-100 dark:bg-green-800 text-green-800 dark:text-green-200 rounded-full p-2 ml-2" aria-label="Delivered">
                        <CheckmarkFilled className="h-4 w-4" aria-hidden="true" />
                      </div>
                    </div>
                  ))}
                  {completedTodayShipments.length > 5 && (
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => setShowAllCompleted(true)}
                      className="mt-2 text-xs"
                    >
                      Show All {completedTodayShipments.length} Completed
                    </Button>
                  )}
                </>
              )}
            </div>
          )}
        </div>
  {/* Pending Card */}
  <div ref={pendingRef} style={{scrollMarginBottom: bottomBarHeight + 24}} className="bg-white/70 backdrop-blur-md rounded-xl shadow-sm border border-white/60 px-4 py-3 dark:bg-slate-800/70 dark:border-slate-600">
    <button className="flex items-center w-full justify-between z-10 relative" onClick={() => setExpandPending(v => { const n=!v; if(!v && pendingRef.current){ pendingRef.current.scrollIntoView({behavior:'smooth', block:'nearest'});} return n; })}>
            <div className="flex items-center gap-3 flex-1 min-w-0">
              <div className="h-6 w-6 text-amber-600 dark:text-amber-400 flex items-center justify-center flex-shrink-0" aria-label="Pending">
                <PendingFilled className="h-5 w-5" aria-hidden="true" />
              </div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-200">Pending</div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <div className="text-2xl font-bold text-gray-900 dark:text-white tabular-nums min-w-[40px] text-right">{pendingDeliveries}</div>
              {expandPending ? <ChevronUp className="h-6 w-6 text-gray-400 dark:text-gray-300" /> : <ChevronDown className="h-6 w-6 text-gray-400 dark:text-gray-300" />}
            </div>
          </button>
          {expandPending && (
            <div className="mt-3 flex flex-col gap-2 z-10 relative">
              {isShipmentsLoading ? (
                <div className="flex flex-col gap-2">
                  {[0,1,2].map((i) => (
                    <div key={`pending-skel-${i}`} className="flex items-center justify-between bg-white/70 dark:bg-slate-900 rounded-lg border border-white/60 dark:border-slate-700 px-3 py-2">
                      <div className="flex-1 min-w-0">
                        <Skeleton className="h-4 w-44 mb-1" />
                        <Skeleton className="h-3 w-28 mb-1" />
                        <Skeleton className="h-3 w-60" />
                      </div>
                      <Skeleton className="h-8 w-16 ml-2 rounded" />
                    </div>
                  ))}
                </div>
              ) : (
                pendingShipments.map((shipment) => (
                  <div key={shipment.awb_number} style={{scrollMarginBottom: bottomBarHeight + 24}} className="flex items-center justify-between bg-white/70 rounded-lg border border-white/60 px-3 py-2 dark:bg-slate-700/70 dark:border-slate-600">
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <div className="font-mono font-bold text-yellow-700 dark:text-yellow-300 text-base">{shipment.awb_number}</div>
                        {shipment.current_status && (
                          <Badge variant="outline" className="text-[10px] px-2 py-0.5 capitalize">
                            {shipment.current_status.replaceAll('_',' ')}
                          </Badge>
                        )}
                      </div>
                      <div className="text-xs text-slate-800 dark:text-slate-200">{shipment.receiver_name}</div>
                      <div
                        role="button"
                        tabIndex={0}
                        aria-expanded={!!expandedAwbs[shipment.awb_number]}
                        onClick={() => toggleAwbExpand(shipment.awb_number)}
                        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleAwbExpand(shipment.awb_number); } }}
                        className={`text-xs text-slate-700 dark:text-slate-300 ${expandedAwbs[shipment.awb_number] ? 'whitespace-normal break-words' : 'truncate cursor-pointer hover:underline'}`}
                      >
                        {shipment.receiver_address}
                      </div>
                      <div className="flex gap-1 mt-1">
                        <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                        <MapsButton address={shipment.receiver_address} />
                      </div>
                    </div>
                    <Button
                      size="sm"
                      className="bg-yellow-500 hover:bg-yellow-600 text-white font-medium rounded-md h-8 px-3 text-xs"
                      onClick={() => router.push(`/courier/update?awb=${shipment.awb_number}`)}
                    >
                      Update
                    </Button>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </div>

    {/* Quick Actions: sticky bottom bar for mobile (minimalist) */}
  <div ref={bottomBarRef} className="fixed bottom-0 left-0 right-0 z-20 bg-gradient-to-tr from-[#1C7FA6] via-[#1969A9] to-[#0D47A1] border-t border-white/10 shadow-[0_-8px_20px_-6px_rgba(0,0,0,0.25)] md:hidden pb-[env(safe-area-inset-bottom)]">
    <div className="grid grid-cols-3 gap-1 p-2">
          <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 rounded-md flex items-center justify-center gap-1" onClick={() => setIsContinuousScanOpen(true)} aria-label="Scan AWB" title="Scan AWB">
            <ScanAlt className="h-4 w-4" aria-hidden="true" />
            <span className="text-[12px]">Scan</span>
          </Button>
          <Button className="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 rounded-md flex items-center justify-center gap-1" onClick={() => setIsBulkModalOpen(true)} aria-label="Bulk Update" title="Bulk Update">
            <Task className="h-4 w-4" aria-hidden="true" />
            <span className="text-[12px]">Update</span>
          </Button>
          <Button className="w-full bg-orange-600 hover:bg-orange-700 text-white font-medium py-2 rounded-md flex items-center justify-center gap-1" onClick={() => setIsPickupFormOpen(true)} aria-label="Pickup" title="Pickup">
            <Package className="h-4 w-4" aria-hidden="true" />
            <span className="text-[12px]">Pickup</span>
          </Button>
        </div>
      </div>

      {/* Floating DLVD Scan Button removed and replaced with header icon */}

            {/* Pending Details Modal */}
      {showPendingDetails && (
        <Dialog open={showPendingDetails} onOpenChange={setShowPendingDetails}>
          <DialogContent className="max-w-md max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Pending Deliveries ({pendingDeliveries})</DialogTitle>
              <DialogDescription>
                Shipments from previous days that need to be delivered
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-2">
              {pendingShipments.map((shipment) => renderShipmentCard(shipment, "pending"))}
            </div>
          </DialogContent>
        </Dialog>
      )}

      {/* Modals */}
      <BulkUpdateModal
        isOpen={isBulkModalOpen}
        onClose={() => setIsBulkModalOpen(false)}
        onSuccess={handleBulkUpdateSuccess}
        currentUser={currentUser}
      />

      <ContinuousScanModal
        isOpen={isContinuousScanOpen}
        onClose={() => setIsContinuousScanOpen(false)}
        onSuccess={handleContinuousScanSuccess}
      />

      <ContinuousScanModal
        isOpen={isDeliveredScanOpen}
        onClose={() => setIsDeliveredScanOpen(false)}
        onSuccess={handleContinuousScanSuccess}
        prefillStatus="delivered"
      />

      {/* Modal All Assignments */}
      <Dialog open={showAllAssignments} onOpenChange={setShowAllAssignments}>
        <DialogContent className="max-w-2xl" showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>All Today's Assignments</DialogTitle>
            <DialogDescription>Complete list of today's assignment AWBs.</DialogDescription>
          </DialogHeader>
          <DialogClose className="absolute right-4 top-4 rounded-full w-8 h-8 bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-600 hover:text-gray-900 border border-gray-200 transition-all">
            <Close size={16} />
            <span className="sr-only">Close</span>
          </DialogClose>
          <div className="max-h-[60vh] overflow-y-auto mt-4 flex flex-col gap-2">
            {sortedAssignments.map((shipment) => (
              <div key={shipment.awb_number} className="flex items-center justify-between bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-100 dark:border-gray-700 px-3 py-2">
                <div>
                  <div className="font-mono font-bold text-blue-700 dark:text-blue-300 text-base">{shipment.awb_number}</div>
                  <div className="text-xs text-gray-500">{shipment.receiver_name}</div>
                  <div
                    role="button"
                    tabIndex={0}
                    aria-expanded={!!expandedAwbs[shipment.awb_number]}
                    onClick={() => toggleAwbExpand(shipment.awb_number)}
                    onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleAwbExpand(shipment.awb_number); } }}
                    className={`text-xs text-gray-400 ${expandedAwbs[shipment.awb_number] ? 'whitespace-normal break-words' : 'truncate cursor-pointer hover:underline'}`}
                  >
                    {shipment.receiver_address}
                  </div>
                  <div className="flex gap-2 mt-1">
                    <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                    <MapsButton address={shipment.receiver_address} />
                  </div>
                </div>
                <Button
                  size="sm"
                  className="bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md h-8 px-3 text-xs"
                  onClick={() => { setShowAllAssignments(false); router.push(`/courier/update?awb=${shipment.awb_number}`); }}
                >
                  Update
                </Button>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>

      {/* Modal All Completed */}
      <Dialog open={showAllCompleted} onOpenChange={setShowAllCompleted}>
        <DialogContent className="max-w-2xl" showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>All Today's Completed Deliveries</DialogTitle>
            <DialogDescription>Complete list of today's completed deliveries ({completedCount} total).</DialogDescription>
          </DialogHeader>
          <DialogClose className="absolute right-4 top-4 rounded-full w-8 h-8 bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-600 hover:text-gray-900 border border-gray-200 transition-all">
            <Close size={16} />
            <span className="sr-only">Close</span>
          </DialogClose>
          <div className="max-h-[60vh] overflow-y-auto mt-4 flex flex-col gap-2">
            {completedTodayShipments.map((shipment) => (
              <div key={shipment.awb_number} className="flex items-center justify-between bg-green-50 dark:bg-green-900 rounded-lg border border-green-100 dark:border-green-700 px-3 py-2">
                <div className="flex-1 min-w-0">
                  <div className="font-mono font-bold text-green-700 dark:text-green-300 text-base">{shipment.awb_number}</div>
                  <div className="text-xs text-green-600 dark:text-green-400">{shipment.status}</div>
                  {shipment.location && (
                    <div className="text-xs text-gray-500 truncate mt-1">{shipment.location}</div>
                  )}
                  <div className="text-xs text-gray-400 mt-1">
                    {new Date(shipment.created_at).toLocaleString('id-ID', { 
                      day: '2-digit', 
                      month: '2-digit', 
                      hour: '2-digit', 
                      minute: '2-digit' 
                    })}
                  </div>
                </div>
                <div className="bg-green-100 dark:bg-green-800 text-green-800 dark:text-green-200 rounded-full p-2 ml-2" aria-label="Delivered">
                  <CheckmarkFilled className="h-5 w-5" aria-hidden="true" />
                </div>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>

      {/* Pickup Form Modal */}
      {isPickupFormOpen && (
        <CourierPickupForm
          onClose={() => setIsPickupFormOpen(false)}
          onSuccess={handlePickupSuccess}
          currentUser={currentUser}
          branchOrigin={null} // Default to pusat branch for couriers
        />
      )}
    </div>
  )
}