"use client"

// Type definitions for courier dashboard
interface User {
  id: string;
  name?: string;
  email?: string;
}

interface Shipment {
  awb_number: string;
  current_status: string;
  receiver_name: string;
  receiver_phone: string;
  receiver_address: string;
  updated_at?: string;
  created_at?: string;
}

interface ShipmentHistory {
  awb_number: string;
  status: string;
  created_at: string;
  location?: string;
}

import { useState, useEffect, useCallback, useRef } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSpinner, faSignOutAlt, faEye, faCheckCircle, faComment, faMapMarkerAlt, faExclamationTriangle, faBarcode } from '@fortawesome/free-solid-svg-icons'
import { Camera, Box, ChevronDown, ChevronUp } from 'lucide-react'
import { supabaseClient } from "@/lib/auth"
import { BulkUpdateModal } from "./bulk-update-modal"
import { ContinuousScanModal } from "./continuous-scan-modal"
import { useToast } from "@/hooks/use-toast"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"

// Function to format phone number for WhatsApp
const formatPhoneForWhatsApp = (phoneNumber: string): string => {
  if (!phoneNumber) return "";
  
  // Remove all non-digit characters
  const cleanNumber = phoneNumber.replace(/\D/g, "");
  
  // If number starts with 0, replace with 62
  if (cleanNumber.startsWith("0")) {
    return "62" + cleanNumber.slice(1);
  }
  
  // If number already starts with 62, keep it
  if (cleanNumber.startsWith("62")) {
    return cleanNumber;
  }
  
  // For any other format, assume it's Indonesian and add 62
  return "62" + cleanNumber;
}

// Component for WhatsApp button
const WhatsAppButton = ({ phoneNumber, recipientName, courierName }: { phoneNumber: string; recipientName: string; courierName: string }) => {
  // Don't show if:
  // 1. Phone number is empty, N/A, or Auto Generated
  // 2. Phone number has less than 10 digits after cleaning
  if (!phoneNumber || 
      phoneNumber === "N/A" || 
      phoneNumber.toLowerCase().includes("auto generated") ||
      phoneNumber.toLowerCase().includes("autogenerated")) {
    return null;
  }
  
  const cleanNumber = phoneNumber.replace(/\D/g, "");
  if (cleanNumber.length < 10) {
    return null;
  }
  
  const formattedNumber = formatPhoneForWhatsApp(phoneNumber);
  const message = encodeURIComponent(`Halo pak ${recipientName}, saya ${courierName} kurir bce express. Yg akan mengirimkan paket bapak. Apakah alamat sudah sesuai di alamat pak? Atau boleh di kirimkan share lokasi nya?`);
  const whatsappUrl = `https://wa.me/${formattedNumber}?text=${message}`;
  
  return (
    <Button
      variant="outline"
      size="sm"
      className="ml-2 h-6 px-2 text-xs bg-green-50 hover:bg-green-100 border-green-200 text-green-700"
      onClick={() => window.open(whatsappUrl, "_blank")}
    >
      <FontAwesomeIcon icon={faComment} className="h-3 w-3 mr-1" />
      WA
    </Button>
  );
};

// Component for Maps button
const MapsButton = ({ address }: { address: string }) => {
  // Don't show if:
  // 1. Address is empty, N/A, or Auto Generated
  // 2. Address is too short (less than 10 characters to ensure it's properly filled)
  if (!address || 
      address === "N/A" || 
      address.toLowerCase().includes("auto generated") ||
      address.toLowerCase().includes("autogenerated") ||
      address.trim().length < 10) {
    return null;
  }
  
  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
  
  return (
    <Button
      variant="outline"
      size="sm"
      className="ml-2 h-6 px-2 text-xs bg-blue-50 hover:bg-blue-100 border-blue-200 text-blue-700"
      onClick={() => window.open(mapsUrl, "_blank")}
    >
      <FontAwesomeIcon icon={faMapMarkerAlt} className="h-3 w-3 mr-1" />
      Maps
    </Button>
  );
};

export function CourierDashboard() {
  const [currentUser, setCurrentUser] = useState<User | null>(null)
  const [completedCount, setCompletedCount] = useState(0)
  const [lastCompletedAwb, setLastCompletedAwb] = useState("")
  const [isBulkModalOpen, setIsBulkModalOpen] = useState(false)
  const [isContinuousScanOpen, setIsContinuousScanOpen] = useState(false)
  const [isDeliveredScanOpen, setIsDeliveredScanOpen] = useState(false)
  const [totalBulkShipments, setTotalBulkShipments] = useState(0)
  const [pendingDeliveries, setPendingDeliveries] = useState(0)
  const [bulkShipmentAwbs, setBulkShipmentAwbs] = useState<Shipment[]>([])
  const [pendingShipments, setPendingShipments] = useState<Shipment[]>([])
  const [showBulkDetails, setShowBulkDetails] = useState(false)
  const [showPendingDetails, setShowPendingDetails] = useState(false)
  const [completedTodayShipments, setCompletedTodayShipments] = useState<ShipmentHistory[]>([])
  const [showCompletedTodayDetails, setShowCompletedTodayDetails] = useState(false)
  const [hasCompletedFirstDelivery, setHasCompletedFirstDelivery] = useState(false)
  const [expandAssignments, setExpandAssignments] = useState(false);
  const [expandPending, setExpandPending] = useState(false);
  const [showAllAssignments, setShowAllAssignments] = useState(false);

  const [isProfileLoading, setIsProfileLoading] = useState(true)
  const [isShipmentsLoading, setIsShipmentsLoading] = useState(false)
  const refreshTimeout = useRef<NodeJS.Timeout | null>(null)
  const locationUpdateInterval = useRef<NodeJS.Timeout | null>(null)

  const router = useRouter()
  const { toast } = useToast()

  const loadShipmentData = useCallback(async (user: User) => {
    setIsShipmentsLoading(true)
    try {
      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const todayISOString = today.toISOString()
      const yesterday = new Date(today)
      yesterday.setDate(yesterday.getDate() - 1)
      const yesterdayISOString = yesterday.toISOString()
      
      const courierId = user?.id
      const courierName = user?.name || user?.email?.split("@")[0] || ""

      // Add timeout to all database queries
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Database timeout')), 15000)
      );

      // Get today's bulk shipments (Today's Assignment) - shipments created today that are not yet delivered/cancelled
      const bulkShipmentsPromise = supabaseClient
        .from("shipments")
        .select("awb_number, current_status, receiver_name, receiver_phone, receiver_address, updated_at")
        .eq("courier_id", courierId)
        .gte("created_at", todayISOString)
        .not("current_status", "in", '("delivered", "cancelled")') // Filter out delivered and cancelled shipments
        .order("updated_at", { ascending: false })
        .limit(50); 

      // Get pending deliveries with only necessary fields - with timeout
      const pendingPromise = supabaseClient
        .from("shipments")
        .select("awb_number, current_status, receiver_name, receiver_phone, receiver_address, created_at")
        .eq("courier_id", courierId)
        .in("current_status", ["out_for_delivery", "shipped"])
        .lt("created_at", todayISOString)
        .order("created_at", { ascending: false })
        .limit(50); // Limit results to improve performance

      // Get completed today with only necessary fields - with timeout
      const completedTodayPromise = supabaseClient
        .from("shipment_history")
        .select("awb_number, status, created_at, location")
        .eq("status", "delivered")
        .ilike("notes", `%${courierName}%`)
        .gte("created_at", todayISOString)
        .order("created_at", { ascending: false })
        .limit(100); // Limit results to improve performance

      // Execute all queries in parallel with timeout
      const [bulkShipmentsResult, pendingResult, completedTodayResult] = await Promise.allSettled([
        Promise.race([bulkShipmentsPromise, timeoutPromise]),
        Promise.race([pendingPromise, timeoutPromise]),
        Promise.race([completedTodayPromise, timeoutPromise])
      ]);

      // Handle bulk shipments result
      if (bulkShipmentsResult.status === 'fulfilled') {
        const { data: bulkShipmentsData, error: bulkShipmentsError } = bulkShipmentsResult.value as { data: Shipment[] | null; error: unknown };
        if (bulkShipmentsError) {
          setTotalBulkShipments(0);
          setBulkShipmentAwbs([]);
        } else {
          setTotalBulkShipments(bulkShipmentsData?.length || 0);
          setBulkShipmentAwbs(bulkShipmentsData || []);
        }
      } else {
        setTotalBulkShipments(0);
        setBulkShipmentAwbs([]);
      }

      // Handle pending deliveries result
      if (pendingResult.status === 'fulfilled') {
        const { data: pendingData, error: pendingError } = pendingResult.value as { data: Shipment[] | null; error: unknown };
        if (pendingError) {
          setPendingDeliveries(0);
          setPendingShipments([]);
        } else {
          setPendingDeliveries(pendingData?.length || 0);
          setPendingShipments(pendingData || []);
        }
      } else {
        setPendingDeliveries(0);
        setPendingShipments([]);
      }

      // Handle completed today result
      if (completedTodayResult.status === 'fulfilled') {
        const { data: completedTodayData, error: completedTodayError } = completedTodayResult.value as { data: ShipmentHistory[] | null; error: unknown };
        if (completedTodayError) {
          setCompletedCount(0);
          setCompletedTodayShipments([]);
          setLastCompletedAwb("");
        } else {
          setCompletedCount(completedTodayData?.length || 0);
          setCompletedTodayShipments(completedTodayData || []);
          if (completedTodayData && completedTodayData.length > 0) {
            const sortedData = [...completedTodayData].sort(
              (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
            );
            setLastCompletedAwb(sortedData[0].awb_number);
          } else {
            setLastCompletedAwb("");
          }
        }
      } else {
        setCompletedCount(0);
        setCompletedTodayShipments([]);
        setLastCompletedAwb("");
      }

    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to load shipment data. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsShipmentsLoading(false);
    }
  }, [toast]);

  const debouncedRefresh = useCallback((user: User) => {
    if (refreshTimeout.current) {
      clearTimeout(refreshTimeout.current)
    }
    
    const timeout = setTimeout(() => {
      loadShipmentData(user)
      refreshTimeout.current = null
    }, 1000)
    
    refreshTimeout.current = timeout
  }, [loadShipmentData])

  // Function to check if courier has completed any deliveries today
  const checkFirstDeliveryStatus = useCallback(async (user: User) => {
    try {
      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const todayISOString = today.toISOString()
      const courierName = user?.name || user?.email?.split("@")[0] || ""

      const { data: completedToday, error } = await supabaseClient
        .from("shipment_history")
        .select("awb_number")
        .eq("status", "delivered")
        .ilike("notes", `%${courierName}%`)
        .gte("created_at", todayISOString)
        .limit(1)

      if (!error && completedToday && completedToday.length > 0) {
        setHasCompletedFirstDelivery(true)
      } else {
        setHasCompletedFirstDelivery(false)
      }
    } catch (error) {
      setHasCompletedFirstDelivery(false)
    }
  }, [])

  const loadUserProfile = useCallback(async () => {
    setIsProfileLoading(true);
    try {
      const { data: sessionData, error: sessionError } = await supabaseClient.auth.getSession();

      if (sessionError) {
        toast({
          title: "Error Session",
          description: sessionError.message || "Failed to get session. Please log in again.",
          variant: "destructive",
        });
        setIsProfileLoading(false);
        return;
      }
      if (!sessionData?.session?.user?.id) {
        router.push("/courier");
        setIsProfileLoading(false);
        return;
      }

      const userId = sessionData.session.user.id;
      const { data: userData, error: userError } = await supabaseClient
        .from("users")
        .select("*")
        .eq("id", userId)
        .single();

      if (userError) {
        toast({
          title: "Error User Data",
          description: userError.message || "Failed to fetch user data. Check RLS on 'users' table.",
          variant: "destructive",
        });
        setIsProfileLoading(false);
        return;
      }

      setCurrentUser(userData);
      setIsProfileLoading(false);
      
      // Check first delivery status
      await checkFirstDeliveryStatus(userData);
      
      loadShipmentData(userData);

    } catch (err: unknown) {
      setIsProfileLoading(false);
      const errorMessage = err instanceof Error ? err.message : "Failed to load user profile. Please try again.";
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive",
      });
    }
  }, [loadShipmentData, router, toast, checkFirstDeliveryStatus]);

  // Geolocation update logic
  const updateCourierLocation = useCallback(async (userId: string) => {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          const { latitude, longitude } = position.coords;
          try {
            // Attempt to update existing record
            const { data: updatedData, error: updateError } = await supabaseClient
              .from('courier_current_locations')
              .update({
                latitude: latitude,
                longitude: longitude,
                updated_at: new Date().toISOString()
              })
              .eq('courier_id', userId)
              .select()
              .maybeSingle(); // Use maybeSingle to get null if no row found

            if (updateError) {
              // If it's a specific error for "no rows updated" (e.g., PGRST116 for PostgREST), then attempt insert
              // Note: supabase-js may not always expose PGRST116 explicitly, but `!updatedData` check handles no matching row.
              const { error: insertError } = await supabaseClient
                .from('courier_current_locations')
                .insert({
                  courier_id: userId,
                  latitude: latitude,
                  longitude: longitude
                });
              if (insertError) {
                toast({
                  title: "Location Save Failed",
                  description: insertError.message || "Could not save current location. Check RLS for INSERT.",
                  variant: "destructive",
                });
              }
            } else if (updatedData) { // If update was successful and data was returned
            } else { // If update was successful but no data was returned (e.g., no matching row for update)
              const { error: insertError } = await supabaseClient
                .from('courier_current_locations')
                .insert({
                  courier_id: userId,
                  latitude: latitude,
                  longitude: longitude
                });
              if (insertError) {
                toast({
                  title: "Location Save Failed",
                  description: insertError.message || "Could not save current location. Check RLS for INSERT.",
                  variant: "destructive",
                });
              }
            }

          } catch (dbError: unknown) {
            const errorMessage = dbError instanceof Error ? dbError.message : "An unexpected database error occurred for location.";
            toast({
              title: "Location DB Error",
              description: errorMessage,
              variant: "destructive",
            });
          }
        },
        (error) => {
          if (error.code === error.PERMISSION_DENIED) {
            toast({
              title: "Geolocation Denied",
              description: "Please allow location access to enable live tracking.",
              variant: "default",
            });
          } else {
            toast({
              title: "Geolocation Error",
              description: error.message || "Could not get current location.",
              variant: "destructive",
            });
          }
        },
        {
          enableHighAccuracy: true,
          timeout: 10000, // 10 seconds
          maximumAge: 0 // No cache
        }
      );
    } else {
      toast({
        title: "Geolocation Not Supported",
        description: "Your browser does not support Geolocation.",
        variant: "destructive",
      });
    }
  }, [toast]);

  useEffect(() => {
    loadUserProfile();

    // Cleanup function
    return () => {
      if (refreshTimeout.current) {
        clearTimeout(refreshTimeout.current);
      }
      if (locationUpdateInterval.current) {
        clearInterval(locationUpdateInterval.current);
        locationUpdateInterval.current = null;
      }
    };
  }, [loadUserProfile]);

  // Separate useEffect for location tracking that depends on hasCompletedFirstDelivery
  useEffect(() => {
    const setupLocationUpdates = async () => {
      if (!hasCompletedFirstDelivery) {
        // Clear any existing interval if tracking should be disabled
        if (locationUpdateInterval.current) {
          clearInterval(locationUpdateInterval.current);
          locationUpdateInterval.current = null;
        }
        return;
      }

      const { data: sessionData } = await supabaseClient.auth.getSession();
      if (!sessionData?.session?.user?.id) return;

      const userId = sessionData.session.user.id;

      // Initial location update
      updateCourierLocation(userId);

      // Set up interval for periodic updates (every 30 seconds)
      if (!locationUpdateInterval.current) {
        locationUpdateInterval.current = setInterval(() => {
          updateCourierLocation(userId);
        }, 30000);
      }
    };

    setupLocationUpdates();

    // Cleanup interval on dependency change
    return () => {
      if (locationUpdateInterval.current) {
        clearInterval(locationUpdateInterval.current);
        locationUpdateInterval.current = null;
      }
    };
  }, [hasCompletedFirstDelivery, updateCourierLocation]);

  const handleLogout = async () => {
    try {
      await supabaseClient.auth.signOut()
      router.push("/courier")
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to logout. Please try again.",
        variant: "destructive",
      });
    }
  }

  const refreshData = () => {
    if (currentUser) {
      debouncedRefresh(currentUser)
    }
  }

  const handleBulkUpdateSuccess = (count: number) => {
    if (currentUser) {
      debouncedRefresh(currentUser)
    }
  }

  const handleContinuousScanSuccess = () => {
    if (currentUser) {
      debouncedRefresh(currentUser)
    }
  }

  const renderShipmentCard = (shipment: Shipment, type: "bulk" | "pending") => {
    const courierName = currentUser?.name || currentUser?.email?.split("@")[0] || ""
    
    return (
      <div key={shipment.awb_number} className="border rounded-lg p-3 mb-2 bg-white">
        <div className="flex justify-between items-start mb-2">
          <div>
            <p className="font-semibold text-sm">{shipment.awb_number}</p>
            <p className="text-xs text-gray-600">{shipment.receiver_name}</p>
          </div>
          <Badge variant={shipment.current_status === "out_for_delivery" ? "default" : "secondary"}>
            {shipment.current_status}
          </Badge>
        </div>
        <p className="text-xs text-gray-500 mb-2">{shipment.receiver_address}</p>
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <WhatsAppButton 
              phoneNumber={shipment.receiver_phone} 
              recipientName={shipment.receiver_name}
              courierName={courierName}
            />
            <MapsButton address={shipment.receiver_address} />
          </div>
          <p className="text-xs text-gray-400">
            {type === "bulk" ? 
              (shipment.updated_at ? new Date(shipment.updated_at).toLocaleDateString() : "") :
              (shipment.created_at ? new Date(shipment.created_at).toLocaleDateString() : "")
            }
          </p>
        </div>
      </div>
    )
  }

  const renderCompletedCard = (shipment: ShipmentHistory) => {
    return (
      <div key={shipment.awb_number} className="border rounded-lg p-3 mb-2 bg-green-50">
        <div className="flex justify-between items-start mb-2">
          <div>
            <p className="font-semibold text-sm">{shipment.awb_number}</p>
            <p className="text-xs text-green-600">{shipment.status}</p>
          </div>
          <Badge variant="outline" className="bg-green-100 text-green-800">
            Delivered
          </Badge>
        </div>
        {shipment.location && (
          <p className="text-xs text-gray-500 mb-2">{shipment.location}</p>
        )}
        <p className="text-xs text-gray-400">
          {new Date(shipment.created_at).toLocaleString()}
        </p>
      </div>
    )
  }

  if (isProfileLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <FontAwesomeIcon icon={faSpinner} spin className="h-8 w-8" />
      </div>
    )
  }

  if (!currentUser) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p>Please log in to access the courier dashboard.</p>
      </div>
    )
  }

  const displayName = currentUser?.name || currentUser?.email?.split("@")[0] || ""
  const emailDisplay = currentUser?.email || ""
  // Logo URL 
  const logoUrl = "/images/bce-logo.png";

  // Sort assignments by created_at ASC (oldest first)
  const sortedAssignments = [...bulkShipmentAwbs].sort((a, b) => {
    const aDate = a.created_at ? new Date(a.created_at).getTime() : 0;
    const bDate = b.created_at ? new Date(b.created_at).getTime() : 0;
    return aDate - bDate;
  });

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      {/* Watermark Background */}
      <div className="fixed inset-0 grid grid-cols-6 gap-x-12 gap-y-8 p-8 pointer-events-none select-none opacity-[0.04] z-0">
        {Array.from({ length: 48 }).map((_, i) => (
          <div key={i} className="text-black dark:text-white -rotate-[36deg]">
            <span className="font-semibold text-sm whitespace-nowrap">BCE Express</span>
          </div>
        ))}
      </div>
      {/* Header */}
      <header className="flex items-center justify-between px-4 py-4 bg-white/70 backdrop-blur rounded-b-2xl shadow-md border-b border-gray-200 sticky top-0 z-10">
        <div className="flex items-center gap-2">
          <img src={logoUrl} alt="BCE Logo" width={32} height={32} className="rounded" />
        </div>
        <div className="flex-1 text-center">
          <span className="font-bold text-lg text-gray-900">{displayName}</span>
          {lastCompletedAwb && (
            <div className="text-xs text-blue-600 mt-1">
              Last AWB job finished: <span className="font-mono">{lastCompletedAwb}</span>
            </div>
          )}
        </div>
        <Button
          variant="ghost"
          onClick={handleLogout}
          className="h-8 px-2 text-xs font-bold text-gray-700"
        >
          <FontAwesomeIcon icon={faSignOutAlt} className="h-5 w-5" />
        </Button>
      </header>

      {/* Quick Stats as Accordions */}
      <div className="flex flex-col gap-3 px-3 py-4">
        {/* Assignments Card */}
        <div className="relative overflow-hidden bg-white/60 backdrop-blur rounded-2xl shadow border border-blue-200 px-4 py-3">
          <div className="absolute left-0 top-0 w-16 h-16 bg-blue-100 rounded-full opacity-30 blur-2xl z-0" />
          <button className="flex items-center w-full justify-between z-10 relative" onClick={() => setExpandAssignments(v => !v)}>
            <div className="flex items-center gap-3">
              <div className="bg-blue-50 rounded-full p-2">
                <Box className="h-7 w-7 text-blue-600" />
              </div>
              <div className="text-xs text-gray-500 font-semibold">Assignments</div>
            </div>
            <div className="text-3xl font-black text-blue-700">{totalBulkShipments}</div>
            {expandAssignments ? <ChevronUp className="h-6 w-6 text-gray-400 ml-2" /> : <ChevronDown className="h-6 w-6 text-gray-400 ml-2" />}
          </button>
          {expandAssignments && (
            <div className="mt-3 flex flex-col gap-2 z-10 relative">
              {sortedAssignments.length === 0 ? (
                <div className="text-gray-400 text-sm">No assignments for today.</div>
              ) : (
                <>
                  {sortedAssignments.slice(0, 5).map((shipment) => (
                    <div key={shipment.awb_number} className="flex items-center justify-between bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-100 dark:border-gray-700 px-3 py-2">
                      <div>
                        <div className="font-mono font-bold text-blue-700 dark:text-blue-300 text-base">{shipment.awb_number}</div>
                        <div className="text-xs text-gray-500">{shipment.receiver_name}</div>
                        <div className="text-xs text-gray-400">{shipment.receiver_address}</div>
                        <div className="flex gap-2 mt-1">
                          <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                          <MapsButton address={shipment.receiver_address} />
                        </div>
                      </div>
                      <Button size="sm" className="bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg" onClick={() => router.push(`/courier/update?awb=${shipment.awb_number}`)}>
                        Update
                      </Button>
                    </div>
                  ))}
                  {sortedAssignments.length > 5 && (
                    <Button variant="ghost" className="w-full text-blue-600 font-bold mt-2" onClick={() => setShowAllAssignments(true)}>
                      View All
                    </Button>
                  )}
                </>
              )}
            </div>
          )}
        </div>
        {/* Completed Card */}
        <div className="relative overflow-hidden bg-white/60 backdrop-blur rounded-2xl shadow border border-green-200 px-4 py-3">
          <div className="absolute left-0 top-0 w-16 h-16 bg-green-100 rounded-full opacity-30 blur-2xl z-0" />
          <div className="flex items-center w-full justify-between z-10 relative">
            <div className="flex items-center gap-3">
              <div className="bg-green-50 rounded-full p-2">
                <FontAwesomeIcon icon={faCheckCircle} className="h-7 w-7 text-green-600" />
              </div>
              <div className="text-xs text-gray-500 font-semibold">Completed</div>
            </div>
            <div className="text-3xl font-black text-green-600">{completedCount}</div>
          </div>
        </div>
        {/* Pending Card */}
        <div className="relative overflow-hidden bg-white/60 backdrop-blur rounded-2xl shadow border border-yellow-200 px-4 py-3">
          <div className="absolute left-0 top-0 w-16 h-16 bg-yellow-100 rounded-full opacity-30 blur-2xl z-0" />
          <button className="flex items-center w-full justify-between z-10 relative" onClick={() => setExpandPending(v => !v)}>
            <div className="flex items-center gap-3">
              <div className="bg-yellow-50 rounded-full p-2">
                <FontAwesomeIcon icon={faExclamationTriangle} className="h-7 w-7 text-yellow-600" />
              </div>
              <div className="text-xs text-gray-500 font-semibold">Pending</div>
            </div>
            <div className="text-3xl font-black text-yellow-600">{pendingDeliveries}</div>
            {expandPending ? <ChevronUp className="h-6 w-6 text-gray-400 ml-2" /> : <ChevronDown className="h-6 w-6 text-gray-400 ml-2" />}
          </button>
          {expandPending && (
            <div className="mt-3 flex flex-col gap-2 z-10 relative">
              {pendingShipments.length === 0 ? (
                <div className="text-gray-400 text-sm">No pending deliveries.</div>
              ) : (
                pendingShipments.map((shipment) => (
                  <div key={shipment.awb_number} className="flex items-center justify-between bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-100 dark:border-gray-700 px-3 py-2">
                    <div>
                      <div className="font-mono font-bold text-yellow-700 dark:text-yellow-300 text-base">{shipment.awb_number}</div>
                      <div className="text-xs text-gray-500">{shipment.receiver_name}</div>
                      <div className="text-xs text-gray-400">{shipment.receiver_address}</div>
                      <div className="flex gap-2 mt-1">
                        <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                        <MapsButton address={shipment.receiver_address} />
                      </div>
                    </div>
                    <Button size="sm" className="bg-yellow-500 hover:bg-yellow-600 text-white font-bold rounded-lg" onClick={() => router.push(`/courier/update?awb=${shipment.awb_number}`)}>
                      Update
                    </Button>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="flex flex-col gap-3 px-3 mb-4">
        <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold text-base py-3 flex items-center justify-center gap-2 rounded-xl shadow" onClick={() => setIsContinuousScanOpen(true)}>
          <FontAwesomeIcon icon={faBarcode} className="h-5 w-5" /> Scan Resi
        </Button>
        <Button className="w-full bg-green-600 hover:bg-green-700 text-white font-bold text-base py-3 flex items-center justify-center gap-2 rounded-xl shadow" onClick={() => setIsBulkModalOpen(true)}>
          <FontAwesomeIcon icon={faEye} className="h-5 w-5" /> Update Manual
        </Button>
      </div>

      {/* Floating DLVD Scan Button (mobile only) */}
      <Button onClick={() => setIsDeliveredScanOpen(true)} className="fixed bottom-5 right-5 z-50 bg-black hover:bg-gray-900 text-white rounded-full shadow-lg p-0 w-16 h-16 flex items-center justify-center sm:hidden">
        <FontAwesomeIcon icon={faBarcode} className="h-10 w-10 text-white" />
      </Button>

            {/* Pending Details Modal */}
      {showPendingDetails && (
        <Dialog open={showPendingDetails} onOpenChange={setShowPendingDetails}>
          <DialogContent className="max-w-md max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Pending Deliveries ({pendingDeliveries})</DialogTitle>
              <DialogDescription>
                Shipments from previous days that need to be delivered
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-2">
              {pendingShipments.map((shipment) => renderShipmentCard(shipment, "pending"))}
            </div>
          </DialogContent>
        </Dialog>
      )}

      {/* Modals */}
      <BulkUpdateModal
        isOpen={isBulkModalOpen}
        onClose={() => setIsBulkModalOpen(false)}
        onSuccess={handleBulkUpdateSuccess}
        currentUser={currentUser}
      />

      <ContinuousScanModal
        isOpen={isContinuousScanOpen}
        onClose={() => setIsContinuousScanOpen(false)}
        onSuccess={handleContinuousScanSuccess}
      />

      <ContinuousScanModal
        isOpen={isDeliveredScanOpen}
        onClose={() => setIsDeliveredScanOpen(false)}
        onSuccess={handleContinuousScanSuccess}
        prefillStatus="delivered"
      />

      {/* Modal All Assignments */}
      <Dialog open={showAllAssignments} onOpenChange={setShowAllAssignments}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>All Today's Assignments</DialogTitle>
            <DialogDescription>Complete list of today's assignment AWBs.</DialogDescription>
          </DialogHeader>
          <div className="max-h-[60vh] overflow-y-auto mt-4 flex flex-col gap-2">
            {sortedAssignments.map((shipment) => (
              <div key={shipment.awb_number} className="flex items-center justify-between bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-100 dark:border-gray-700 px-3 py-2">
                <div>
                  <div className="font-mono font-bold text-blue-700 dark:text-blue-300 text-base">{shipment.awb_number}</div>
                  <div className="text-xs text-gray-500">{shipment.receiver_name}</div>
                  <div className="text-xs text-gray-400">{shipment.receiver_address}</div>
                  <div className="flex gap-2 mt-1">
                    <WhatsAppButton phoneNumber={shipment.receiver_phone} recipientName={shipment.receiver_name || "Customer"} courierName={displayName} />
                    <MapsButton address={shipment.receiver_address} />
                  </div>
                </div>
                <Button size="sm" className="bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg" onClick={() => { setShowAllAssignments(false); router.push(`/courier/update?awb=${shipment.awb_number}`); }}>
                  Update
                </Button>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}