// Centralized agent lists for branches

export const baseAgentListBangka: string[] = [
  "555 in2 PKP",
  "BELINYU AGEN",
  "KOLIM SLT",
  "SUNGAILIAT AGEN",
  "TOBOALI (ABING)",
  "KOBA (ABING)",
  "JEBUS (MARETTA)",
  "JEBUS (ROBI SAFARI)",
  "MENTOK (LILY)",
  "ACHUANG KOBA",
  "BCE TONI WEN",
  "BAYAR BANGKA DARAT",
  "BAYAR JKT DARAT",
  "7FUN SLT",
  "ASIONG SAUCU",
  "AFUK BOM2 SAUCU",
  "TONI SAUCU",
  "AFO SAUCU",
  "KEN KEN SAUCU",
  "ADI BOB SAUCU",
  "AFEN SAUCU",
  "AHEN SAUCU",
  "AKIUNG SAUCU",
  "ALIM SAUCU",
  "ALIONG SAUCU",
  "APHING SAUCU",
  "ATER SAUCU",
  "BULL BULL SAUCU",
  "CHANDRA SAUCU",
  "DANIEL SAUCU",
  "DEDI PEN SAUCU",
  "EDO SAUCU",
  "HENDRA ABOY SAUCU",
  "NYUNNYUN SAUCU",
  "RIO SAUCU",
  "YOPY SAUCU",
  "ACN SNACK",
  "ACS SNACK",
  "OW SNACK",
  "SNACK 168",
  "ADOK RUMAH MAKAN",
  "JI FUN MESU",
  "BE YOU",
  "BEST DURIAN",
  "BOM BOM BUAH",
  "TOKO AGUNG",
  "AINY OTAK OTAK",
  "APO SPX SLT",
  "AFUI SPX P3",
  "ASUN OTAK OTAK",
  "BANGKA CITRA SNACK",
  "BANGKA BULIONG SNACK",
  "BILLY JNE",
  "TOKO BINTANG 5",
  "CE NIE NIE",
  "CENTRAL FOOD",
  "CENTRAL NURSERY BANGKA",
  "CHIKA",
  "GLORIA MOTOR",
  "HELDA ASIAT",
  "HANS KOKO DURIAN",
  "KIM NYUN AGEN",
  "AFAT SUBUR",
  "MR ADOX",
  "IN IN",
  "PEMPEK KOKO LINGGAU",
  "PEMPEK SUMBER RASA",
  "PEMPEK WONG KITO",
  "RAJAWALI (AKHIONG)",
  "THEW FU CAU AWEN",
  "THEW FU CAU PAULUS",
  "COD UDARA",
  "COD LAUT",
  "YENNY",
  "TATA",
  "PHING BCE",
  "AJIN",
  "ALUN AGEN",
  "ALING BINTANG",
  "NINA SARJU",
  "NONOCO RESTO",
  "GETAS PIALA",
  "BAKPAO AHON",
  "BAKPAO ABUN",
  "MY SNACK",
  "KO FAT SUBUR",
  "AF BAKWAN",
  "NOVI / IN IN",
  "VICHA FOOD",
  "WW Snack",
  "PC 46 / Elly",
  "Devi Snack",
  "Bbs Snack",
  "Jajanan Khas Bangka",
  "Pempek Wongkito",
  "Cece Rambat",
  "Sofyan Bakpaw",
  "Bom2 Buah",
  "Dedi/achong",
  "SHM AGEN",
  "CE MEI NI",
  "AFun Mesu",
  "Toko Amin Snack",
  "Fong2 Snack",
  "Ahap Walet",
  "Kuliner Bangka",
  "Vita Agen",
  "Ko Ate"
];

export const baseAgentListTanjungPandan: string[] = [
  "COD",
  "TRANSFER",
  "CASH",
  "Wijaya Crab"
];

export const baseAgentListCentral: string[] = [
  "OTTY OFFICIAL",
  "UDR CASH",
  "SEA CASH",
  "GLC UDR TRF",
  "GLC SEA TRF",
  "COD UDR",
  "COD SEA",
  "KMY UDR TRF",
  "KMY SEA TRF",
  "KARTINI KIKI",
  "DUTA GARDEN FRENITA",
  "FELLISIA PORIS EX 3",
  "CITRA 3 RENY",
  "HENDI",
  "PRALITA",
  "SALIM",
  "ISKANDAR",
  "IMAM",
  "DONI",
  "HERFAN",
  "EZZA",
  "YANDRI",
  "DIKY",
  "YOS",
  "INDAH SUSHI TIME",
  "CENTRAL NURSERY BANGKA",
  "MAMAPIA",
  "AMELIA PEDINDANG",
  "HENDRY LIMIA",
  "JESS DOT",
  "SEPIRING RASA BASO",
  "CHRISTINE PADEMANGAN",
  "AMERTHA / HOLAI RESTO"
];
